name: Build Binaries
on: 
  push:
    tags:
      - "v*.*.*"

jobs:
  build_for_pi:
    name: Raspberry Pi

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf
      - name: Rename binary
        run: mv target/armv7-unknown-linux-gnueabihf/release/cf_ddns cf_ddns-armv7-pi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: cf_ddns-armv7-pi
