name: Build Binaries
on: 
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build_for_pi:
    name: Raspberry Pi

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf
      - name: Rename binary
        run: mv target/armv7-unknown-linux-gnueabihf/release/cf_ddns cf_ddns-armv7-pi
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: cf_ddns-armv7-pi application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
